### ISSUE TITLE
Getter functions for sequencer fields

### ISSUE THREAD

**Issue by BkChoy** [MetisProtocol/metis-sequencer-contract#5]
Currently to access the fields of a sequencer, we have to call `SequencerInfo.sequencers()` which returns the entire struct. It would be great to have a couple additional getters so we don't have to load the entire struct to read a single field. Specifically, it would be useful to have a getter for `Sequencer.amount` and `Sequencer.reward`

**Comment by ericlee42** [comment]
Hi, Thanks for the feedback.

Do you have a special use case for that?

We have deployed the contracts on mainnnet, and we don't have a plan to change them for now

**Comment by BkChoy** [comment]
We are building a liquid staking protocol and need to periodically query the sequencer amount and rewards to update the accounting in our contracts. But that's fair enough, I wasn't aware you already deployed to mainnet

**Comment by ericlee42** [comment]
close due to we don't have a plan to support it.
